version: '3'

networks:
  meshnetwork: {}

services:
  proxy:
    build:
      context: ./envoy-proxy
      dockerfile: Dockerfile
    volumes:
      - ./envoy-proxy/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/debug/wasmistioplugin.wasm:/etc/wasmistioplugin.wasm
    networks:
      - meshnetwork
    ports:
      - "18000:80"

  app:
    build:
      context: ./node-service
      dockerfile: Dockerfile
    networks:
      - meshnetwork
    ports:
      - 4000:4000
